#!/usr/bin/python
# -*- coding: utf8 -*-

# guadaquiz2
# Un simple juego de preguntas pensado para pantalla tactil
# Author: Alfonso E.M.
# License: Free (GPL) 
# Version: 2.0 - /Apr/2007

import pygame
import os,sys
import getopt
import random
import Tools 
import Gui


 
# MAIN INITIALIZATION

def main():

  gui=Gui.Gui()

  questionfile=""
  appdir=os.path.dirname(sys.argv[0])
  questionfiles=os.listdir(appdir+"/questions")

  ok=0
  wrong=0

  gui.show_intro()

  while 1:
   questionfile=""
   while questionfile[0:1] != "q":
     questionfile=random.choice(questionfiles)
   try:
       qfile=open(appdir+"/questions/"+questionfile) 
   except:
      sys.exit("ERROR: can't open question file "+questionfile)
   question =qfile.readline().replace("\n","")
   question=unicode(question,'utf-8')
   answer1=qfile.readline().replace("\n","")
   answer1=unicode(answer1,'utf-8')
   answer2=qfile.readline().replace("\n","")
   answer2=unicode(answer2,'utf-8')
   answer3=qfile.readline().replace("\n","")
   answer3=unicode(answer3,'utf-8')
   right_answer=qfile.readline()
   qfile.close

   gui.show_question(question,answer1,answer2,answer3)
   answer=gui.wait_for_answers()
   if answer == right_answer:
      ok=ok+1
   else:
      wrong=wrong+1

   if answer == "A":
      show = answer1
   elif answer == "B":
      show = answer2
   elif answer == "C":
      show = answer3
   gui.show_result(show,answer,right_answer)

 

if __name__ == '__main__': main()
